"""Update report model for new ML features

Revision ID: 2b1c9c789797
Revises: 
Create Date: 2026-09-20 11:40:48.534089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b1c9c789797'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('crude_fiber', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('total_phenolics', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('total_flavonoids', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('dpph', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('fruit_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'fruit_type')
    op.drop_column('reports', 'dpph')
    op.drop_column('reports', 'total_flavonoids')
    op.drop_column('reports', 'total_phenolics')
    op.drop_column('reports', 'crude_fiber')
    # ### end Alembic commands ###
